# Install with cache
name: Run unit tests

on:
  workflow_run:
    workflows:
      - Ruff code check
    types:
      - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
        # exclude:
        #   - os: windows-latest
        #     python-version: "3.9"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: print
      run: echo "hola mundo"