---
name: Unittests

on:
  workflow_run:
    workflows:
      - Ruffcheck
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
    - name: Echo Something
      run: echo "Hello, this is an example echo!"
      run: echo "Hello, this is an example echo!"
